logging.level:
  root: warn
  org.atmosphere: warn
  de.grimsi.gameyfin: info
  de.grimsi.gameyfin.GameyfinApplicationKt: warn
  org.springframework.security.config.annotation.authentication.configuration.InitializeUserDetailsBeanManagerConfigurer: ERROR

server:
  port: 8080
  servlet:
    session:
      tracking-modes: cookie

management:
  server:
    port: 8081
  endpoints:
    web:
      exposure:
        include: restart, health, info, metrics, prometheus
  endpoint:
    pause:
      enabled: false
    restart:
      access: unrestricted

spring:
  # Workaround for https://github.com/vaadin/hilla/issues/842
  devtools.restart.additional-exclude: dev/hilla/openapi.json
  jpa:
    # defer-datasource-initialization: true
    hibernate:
      ddl-auto: update
    open-in-view: true
  mustache:
    check-template-location: false
  sql.init.mode: always
  datasource:
    username: gfadmin
    password: gameyfin
    db-name: gameyfin_db
    url: jdbc:h2:file:./db/${spring.datasource.db-name}
    driverClassName: org.h2.Driver
  content:
    fs.filesystem-root: ./data/
  application:
    name: Gameyfin
  threads:
    virtual.enabled: true
  mvc:
    async.request-timeout: 0

vaadin:
  # To improve the performance during development.
  # For more information https://vaadin.com/docs/flow/spring/tutorial-spring-configuration.html#special-configuration-parameters
  allowed-packages:
    - com.vaadin
    - org.vaadin
    - dev.hilla
  pnpm:
    enable: false