services:
  gameyfin:
    image: ghcr.io/gameyfin/gameyfin:2
    container_name: gameyfin
    environment:
      # Generate a new APP_KEY using the command `openssl rand -base64 32` or similar.
      APP_KEY: <you app key here>
    volumes:
      - "./db:/opt/gameyfin/db"
      - "./data:/opt/gameyfin/data"
      - "./logs:/opt/gameyfin/logs"
      - "./plugindata:/opt/gameyfin/plugindata"
      - <mount your library folder(s) here>
    ports:
      - "8080:8080"
      # If you plan to use the included torrent plugin, uncomment the following lines:
      # - "6969:6969"
      # - "6881:6881"
