gameyfin:
  user: admin
  password: password

logging:
  level:
    de.grimsi: debug
    # org.springframework.web.reactive.function.client.ExchangeFunctions: debug

spring.mvc.log-request-details: true